#!/usr/bin/env python3
"""
Package the edition as a single standalone HTML file.

Inlines the stylesheet, the front-end script, and all five data
artifacts into one self-contained page that opens directly from disk
(file://) with no server, no fetches, and no Python required by the
reader. The front end prefers the embedded data block over fetching
(see loadData() in docs/assets/js/frus.js), so one script serves both
the served site and this artifact.

Pipeline bookkeeping fields that the front end never reads
(persons[].tei_source) are stripped from the embedded copy to keep the
file smaller; the served site's data is untouched.

Output: docs/reykjavik-40-standalone.html (also downloadable from the
deployed site).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

DOCS = Path("docs")
DATA = Path("data")
OUT = DOCS / "reykjavik-40-standalone.html"

CSS_LINK = '<link rel="stylesheet" href="assets/css/frus.css" />'
JS_TAG = '<script src="assets/js/frus.js" type="module"></script>'


def embeddable_json(payload: dict) -> str:
    """Compact JSON, safe inside a <script> element."""
    return json.dumps(payload, separators=(",", ":"), ensure_ascii=False).replace("</", "<\\/")


def slim_docs(records: list) -> list:
    out = []
    for r in records:
        r = dict(r)
        r["persons"] = [
            {k: v for k, v in p.items() if k != "tei_source"}
            for p in r.get("persons", [])
        ]
        out.append(r)
    return out


def main() -> int:
    template = (DOCS / "index.html").read_text()
    css = (DOCS / "assets" / "css" / "frus.css").read_text()
    js = (DOCS / "assets" / "js" / "frus.js").read_text()
    if "</script" in js.lower():
        print("error: frus.js contains a literal </script>, unsafe to inline", file=sys.stderr)
        return 1

    # The declassified PDF manifest is optional: the standalone still
    # builds without it, just with the PDF library view hidden.
    foia_pdfs_path = DATA / "foia_pdfs.json"
    foia_pdfs = json.loads(foia_pdfs_path.read_text()) if foia_pdfs_path.exists() else None

    # Participant portraits are likewise optional and provenance-gated.
    portraits_path = DATA / "portraits.json"
    portraits = json.loads(portraits_path.read_text()) if portraits_path.exists() else None

    payload = {
        "docs": slim_docs(json.loads((DATA / "frus_core.json").read_text())),
        "register": json.loads((DATA / "register.json").read_text()),
        "stage": json.loads((DATA / "summit_stage.json").read_text()),
        "timeline": json.loads((DATA / "timeline.json").read_text()),
        "manifest": json.loads((DATA / "manifest.json").read_text()),
        "foiaPdfs": foia_pdfs,
        "portraits": portraits,
    }

    for marker in (CSS_LINK, JS_TAG):
        if marker not in template:
            print(f"error: marker not found in docs/index.html: {marker}", file=sys.stderr)
            return 1

    html = template.replace(CSS_LINK, f"<style>\n{css}\n</style>")
    html = html.replace(
        JS_TAG,
        '<script id="embedded-data" type="application/json">'
        + embeddable_json(payload)
        + f'</script>\n  <script type="module">\n{js}\n</script>',
    )
    html = html.replace(
        "<title>",
        "<!-- Standalone single-file edition: generated by scripts/build_standalone.py. "
        "All data embedded; opens from disk with no server. -->\n  <title>",
    )

    OUT.write_text(html)
    print(f"{OUT}  {OUT.stat().st_size / 1_048_576:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
